### ISSUE TITLE
"Help file not found" when using option -s

### ISSUE THREAD

**Issue by ixb11170** [Yepkit/ykush#11]
If i list all attached ykush boards using -l, it works and returns 2 serial numbers. However if i try to use any of those serial numbers with -s, it always returns "Help file not found". I'm using it on Raspberry pi 3b+, with Raspbian Stretch.

**Comment by yep1** [comment]
Hi,
can you "paste" here the exact command you are issuing.

Is it something like the following?
`ykushcmd -s YK000001 -d 1`
 
Thanks

**Comment by ixb11170** [comment]
Any command preceded by -s serial_number gives the same result. For example I tried:

    ykushcmd -s YK23300 -g 1

Whereas these work fine:

    ykushcmd -l
    ykushcmd -g 1

Cheers.

**Comment by yep1** [comment]
Hi,
are you using the latest commit?
We are not being able to replicate the issue with the latest commit.

Thanks and regards.

**Comment by ixb11170** [comment]
Sorry for the confusion, I had an older commit indeed. I'd downloaded the source files from yepkit website instead of using git. All working fine now.

**Comment by yep1** [comment]
I'm happy all is working now.
Best Regards
