### ISSUE TITLE
A new release?

### ISSUE THREAD

**Issue by lkundrak** [Yepkit/ykush#12]
There's quite some development in the Git tip.
I'm wondering if you could tag a release?

Thanks

**Comment by lkundrak** [comment]
Hello. Any chances of addressing this?

Thank you

**Comment by yep1** [comment]
Hi,
we are testing some developments and will be doing a new tag release by the end of the week.
Best Regards

**Comment by nullr0ute** [comment]
Hey @yep1 how is that release looking?

**Comment by nobodyinperson** [comment]
Please add a release or at least a tag for 1.2.2. Simplifies packaging.

**Comment by yep1** [comment]
Hello,
We added the tag release for version 1.2.2.
Best regards
