### ISSUE TITLE
ykushcmd returns no YKUSH board found for YKUSH 3

### ISSUE THREAD

**Issue by bachnguyen93** [Yepkit/ykush#14]
I ran the "sudo ykushcmd -l" but it returns no board found. Alternatively I installed pykush and it is able to detect the board. So I think the problem lies in the ykushcmd for linux that could not detect the board. I also tried ykushcmd.exe on Windows and it still works.

**Comment by yep1** [comment]
Hi,
the command to list YKUSH3 boards is the following:

sudo ykushcmd ykush3 -l

Regards.

**Comment by bachnguyen93** [comment]
Hi, 
Thanks it works. That was silly of me. So you have to identify the model for it to work, quite different from Windows version and pykush.
