### ISSUE TITLE
YKUSH initial power state

### ISSUE THREAD

**Issue by serjepatoff** [Yepkit/ykush#16]
Not actually an issue, but a tech question.

Are 3 downstream USB ports initially-powered-on or initially-powered-off just after ext PWR is supplied to YKUSH? I need a hub like this, but strictly with initially-powered-off downstream ports that I will turn on explicitly, one-after-one, to prevent power spike and be able to use less powerful PSU. Usage scenario is like this: 2 YKUSH boards connected to 2 USB ports of mini–ITX motherboard, with 6 USB devices draining about 1A at boot time and 0.3A–0.4A after that. If these USB devices start at the same time, there will be 30W power spike.

Is it possible on YKUSH? (For example, with PIC16F firmware modification)?

**Comment by yep1** [comment]
Hello Sergei,

thanks for your contact.

Yes it is possible with YKUSH.

Natively the YKUSH boards have the downstream ports switched-ON by the default. This behaviour can be changed by loading a firmware which implements the downstream ports switched-OFF by default.

You can purchase the YKUSH normally in our website and once the order is confirmed/concluded send an email to tech.suppport@yepkit.com stating that you want the boards of order XXXXX to be loaded with the firmware for default-OFF downstream ports.

Alternatively you can use YKUSH3 boards which are configurable by USB. With YKUSH3 boards you can configure them yourself to any mix of default ON or OFF in the downstream ports.

If you need any additional information or support let us know.

Best Regards.

**Comment by serjepatoff** [comment]
Thank you very much for so quick reply!

I already ordered 2 YKUSH boards for testing, so can you provide the firmware for default-OFF behaviour that I can flash by myself? (Or place in firmware code to modify).

PS. Sorry for disturbing you 2 times with the same question (on github and via tech support email).
I just want that everybody know about this nuance, not just me, and that's why I repeated this question here.

**Comment by shg-rtx** [comment]
I am in the same situation @yep1 @serjepatoff  Did you get the firmware with this configuration? Rather frustrated over the default behavior
