### ISSUE TITLE
Additional depenency on linux

### ISSUE THREAD

**Issue by brtietz** [Yepkit/ykush#17]
I was following the instructions here: https://www.yepkit.com/learn/setup-guide-ykush to install the command application, and got the error `fatal error: libudev.h: No such file or directory` when running `./build.sh`.

I was able to solve this by installing libudev (`sudo apt-get install libudev-dev`), but wanted to give you a heads up that all of the relevant dependencies weren't listed in your instructions. Thanks!

**Comment by yep1** [comment]
Hi, thanks for the input.
In the new commits a change has been made and for Linux the ykushcmd is no longer using hidapi library, so the libudev should not be an issue any more.
Best regards.
