### ISSUE TITLE
Help file not found.

### ISSUE THREAD

**Issue by likewise** [Yepkit/ykush#19]
commit c585d24553f5ca4cf52f6cd54ecefdf5ff9947f9

sudo build.sh
sudo install.sh

both ran without problems.

But I cannot run the command

16:30 $ sudo ykushcmd -h

Help file not found.

16:30 $ sudo ykushcmd 

Help file not found.

**Comment by yep1** [comment]
Hi, thanks for you comment.
The latest commits have addressed this and help is hard-coded overcoming that issue.
