### ISSUE TITLE
Feature request: return code

### ISSUE THREAD

**Issue by JoernMueller** [Yepkit/ykush#20]
Currently the program seems to return always 0, which generally indicates success. In the context of running ykush in shell scripts or automation tools it would be a significant improvement if the application would return non-zero status code(s) if the command could not be executed as expected.

**Comment by yep1** [comment]
Hi, thanks for the input.
The current commit has incorporated this suggestion. It is returning negative values on error and zero on success.
The error code map will be documented and soon made available in the ykushcmd reference manual at https://www.learn.yepkit.com/reference/ykushcmd-reference-ykush/1/2

**Comment by JoernMueller** [comment]
Thank you very much for your fast response. As far as I can see the value still needs to be returned from `main()´.

**Comment by yep1** [comment]
Yes it did. Thanks for bringing it to our attention. Best regards.
