### ISSUE TITLE
Memory leaks?

### ISSUE THREAD

**Issue by JoernMueller** [Yepkit/ykush#21]
The objects created in  ykush/2/3.cpp using `new` seem never to be freed up, at least if there is not any auto-magically stuff going on in the background I have overlooked. Most simple fix:
Replace dynamic allocations like
`Ykush2 *ykush = new Ykush2(0xEFED);`
with a simple instance that gets deleted when the scope is left
`Ykush2 ykush(0xEFED);`
1st alternative: use smart pointers
2nd alternative: use `delete ykush` when the object is no longer required.

**Comment by yep1** [comment]
Hi, thanks for your comments. The issue has been addressed by commits present in the latest push.
