### ISSUE TITLE
Firmware update.

### ISSUE THREAD

**Issue by Misiek1992** [Yepkit/ykush#34]
Hello. 

I need to update my ykush board to work with pykush library:
ykush\ykushcmd.exe ykush3 --firmware-version
Firmware version-0.0.0

ykush\ykushcmd.exe ykush3 -l
Attached YKUSH Boards:
1. Board found with serial number: YK3B2104

I have tried to contact You using contact on website but without success. 
I need a hex file to update firmware. 

Best Regards,

Michal

**Comment by yep1** [comment]
Hi Michal,

We have received you tech support request and replied to it by email.
Can you please check if it is blocked in your email spam box.

Thanks
