### ISSUE TITLE
Unable to control ykush board

### ISSUE THREAD

**Issue by gcornut** [Yepkit/ykush#4]
I've built the ykushcmd in a raspbian linux running on a Raspberry pi 3 and I can't control the ykush connected to it.

When listing boards:
```sh
$ ./bin/ykushcmd -l

Attached YKUSH Boards

---------------------
YKUSH device found with Serial Number: (null)
  Manufacturer: (null)
  Product:      (null)
```

When getting the status of port 1:
```sh
$ ./bin/ykushcmd -g 1

Unable to get port status for port 1
```

**Comment by yep1** [comment]
Hi,

please try running the command as admin, for example:

$sudo ykushcmd -l

Best Regards

**Comment by gcornut** [comment]
I totally forgot the sudo was necessary...
Thank you very much!
