### ISSUE TITLE
Downstream port 0 is OFF

### ISSUE THREAD

**Issue by mpoulak** [Yepkit/ykush#8]
Hello,
I'm facing an issue with the YKUSH board connected to a Debian jessie apu2 board.
The board works perfectly in an Ubuntu computer, however when i plug it in the apu2,
i can see the device with "sudo ./ykushcmd -l", but i'm getting:
"Downstream port 0 is OFF"
when i'm trying to do other up/down processes  to any port (e.g. "sudo ./ykushcmd -g 1").
Any ideas? Is it possible the usb hub to be locked somehow?

**Comment by yep1** [comment]
Hi Marios,

if you can see the board using the ykushcmd -l command then the board is correctly attached to the host and it is not "locked down".

The issue seams to be on the software/host side which is not claiming the YKUSH control device. Did you build the application on Debian using the build.sh script?

Thanks.

Best Regards.

**Comment by mpoulak** [comment]
Yes of course and with the same procedure, i have built the application on a different Ubuntu computer and it is working fine. 
This "Downstream port 0 is OFF" message is the message i also get when i am trying to up/down a non-available port (e.g. 4,5,6) in Ubuntu computer, that's why i thought that something could be blocked or locked in Debian.
Thanks.

**Comment by mpoulak** [comment]
I finally figure it out. 
There was another program (called usb-monitor) running by default in Debian apu and that was causing the problem.
Thank you.
